version: '3.8'
services:
  parser:
    build:
      context: ./parser/client
    environment:
      PORT: 4000
    depends_on:
      - db
      - nginx
      - apiparser
    restart: always
  apiparser:
    build:
      context: ./parser/server
    environment:
      PORT: 4001
      DATABASE_URL_SHOP: mysql://adminsbtest:adminsbtest@db:3306/sb
      DATABASE_URL_PARSER: mysql://adminsbtest:adminsbtest@db:3306/sb-parser
      SECRET: ade8959dd56e2b039e862b59ec6c0e3eb0879f456c7a5874467ea6677e34e219
      COOKIE_DOMAIN: adminsb.space
      EXPIRES_IN: 15d
      BOT_ID: super-brand-parser
    volumes:
      - ./static:/static
    depends_on:
      - db
      - nginx
      - server
    restart: always
  admin:
    build:
      context: ./admin
    environment:
      PORT: 3000
    depends_on:
      - db
      - nginx
    restart: always
  server:
    build:
      context: ./server
    environment:
      PORT: 5000
      DATABASE_URL: mysql://adminsbtest:adminsbtest@db:3306/sb
      SECRET: ade8959dd56e2b039e862b59ec6c0e3eb0879f456c7a5874467ea6677e34e219
      STATIC_FILES_PATH: /static
      SMTP_EMAIL: gryaznykh.ivan@gmail.com
      SMTP_PASSWORD: qunzzygesomjogxd
      COOKIE_DOMAIN: adminsb.space
      EXPIRES_IN: 15d
    volumes:
      - ./static:/static
    depends_on:
      - db
      - nginx
    restart: always
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    restart: unless-stopped
  db:
    image: mysql:8
    environment:
      MYSQL_USER: adminsbtest
      MYSQL_ROOT_PASSWORD: adminsbtest
      MYSQL_PASSWORD: adminsbtest
      MYSQL_DATABASE: sb
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
volumes:
  db:
    driver: local
