version: '3.8'
services:
  admin:
    build:
      context: ./admin
    environment:
      NEXT_PUBLIC_API_URL: https://adminsb.space
      NEXT_PUBLIC_STATIC_URL: https://static.adminsb.space
    depends_on:
      - db
      - nginx
    restart: always
  server:
    build:
      context: ./server
    environment:
      PORT: 5000
      COOKIE_DOMAIN: adminsb.space
      DATABASE_URL: mysql://adminsbtest:adminsbtest@db:3306/sb
      SECRET: ade8959dd56e2b039e862b59ec6c0e3eb0879f456c7a5874467ea6677e34e219
      STATIC_FILES_PATH: /static
      SMTP_EMAIL: gryaznykh.ivan@gmail.com
      SMTP_PASSWORD: qunzzygesomjogxd
      EXPIRES_IN: 15d
    volumes:
      - ./static:/static
    depends_on:
      - db
      - nginx
    restart: always
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    restart: unless-stopped
  db:
    image: mysql:8
    command: --lower_case_table_names=1
    environment:
      MYSQL_USER: adminsbtest
      MYSQL_ROOT_PASSWORD: adminsbtest
      MYSQL_PASSWORD: adminsbtest
      MYSQL_DATABASE: sb
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
volumes:
  db:
    driver: local