import Head from 'next/head'
import MainLayout from '../components/layouts/Main'
import { useAppSelector } from '../hooks/store'


export default function Index() {
    const auth = useAppSelector(state => state.auth)

    return (
        <MainLayout>
            <Head>
                <title>Главная</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="px-6 my-4 max-w-3xl mx-auto space-y-4">
                <div className="font-bold text-xl">Добро пожаловать!</div>
                <div className="">Version 1.0.0</div>
            </div>
        </MainLayout>
    )
}
