import Head from 'next/head'
import MainLayout from '../components/layouts/Main'
import { useAppSelector } from '../hooks/store'


export default function Index() {
    const auth = useAppSelector(state => state.auth)

    return (
        <MainLayout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className=""></div>
        </MainLayout>
    )
}
