import Head from 'next/head'
import Image from 'next/image'
import MainLayout from '../components/layouts/Main'


function Index() {
    return (
        <MainLayout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="">123</div>
        </MainLayout>
    )
}

export default Index
