import Head from 'next/head'
import { wrapper } from '../store'
import { testService, useTestQuery } from '../services/test.service'
import MainLayout from '../components/layouts/Main'
import SaleUpTo30Precent from '../components/banners/SaleUpTo30Precent'
import CollectionPreview from '../components/collections/CollectionPreview'

export default function Index() {
    const { data } = useTestQuery({})

    return (
        <MainLayout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="">
                <SaleUpTo30Precent />
                <CollectionPreview
                    title="Новые поступления SS'22"
                    collectionId="123"
                />
                <CollectionPreview
                    title="Встречаем Хэллоуин 2022 вместе с Sortage"
                    collectionId="123"
                />
                <CollectionPreview
                    title="Air Jordan 1 Mid"
                    collectionId="123"
                />
            </div>
        </MainLayout>
    )
}

export const getServerSideProps = wrapper.getServerSideProps(
    (store) => async (context) => {

        // await store.dispatch(testService.endpoints.test.initiate({}))

        return {
            props: {},
        };
    }
);
